### ISSUE TITLE
Use str.title() on parseDataTable keys

### ISSUE THREAD

**Issue by patcon** [opencivicdata/python-legistar-scraper#22]
Seems that at one point, the NYC scraper's website column was called "Web site", but it now seems to be "Web Site". SF also uses "Web Site". Perhaps we could title-case or lower-case the headers for more consistency?

EDIT: https://github.com/opencivicdata/scrapers-us-municipal/blob/master/nyc/people.py#L86

**Comment by fgregg** [comment]
Huh? The NYC scraper is working fine.

**Comment by patcon** [comment]
Yeah, I'm confused. But you see what I mean, right?

https://legistar.council.nyc.gov/MainBody.aspx show "Web Site". Code checks for `person['Web site']`. Unless I'm misunderstanding something fundamental about python (which may be the case -- it's pretty new to me), that should be an issue, right?

**Comment by fgregg** [comment]
We are extracting the data from the person detail page:
http://legistar.council.nyc.gov/PersonDetail.aspx?ID=125488&GUID=57421577-C58B-487E-BBD1-BC7522FEE828&Search=

**Comment by patcon** [comment]
Ah, [found it](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/people.py#L27). So both keys exist. OK, cool.
