### ISSUE TITLE
The API improves, may be able to get away with not scraping web

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/python-legistar-scraper#92]
The legistar webapi has some new features that may obviate the need for so much scraping of the web.

So far, I've noticed that event endpoints have a comment field and a link to the event web url.

**Comment by skorasaurus** [comment]
Have you found a changelog anywhere (or does Granicus never even release one?)

**Comment by fgregg** [comment]
I haven't.

**Comment by fgregg** [comment]
Resources we are currently getting from the InSite

- The InSite URL for the event https://github.com/opencivicdata/scrapers-us-municipal/blob/master/lametro/events.py#L108-L112


So it looks like there are at least some variables that we need from the web but it does look get rid of `_scrapeWebCalendar` and instead do something like this in 

```python
def events(...):
    ...
    for api_event in self.api_events(since_datetime):
        ...
        web_event = self.web_scraper.event_detail(api_event['EventInSiteURL'])
```

That, confidently visit the InSite detail page for an event only when we need to.

This should give us a more confidence than the approach of trying to connect events scraped in two ways. It should also make for faster scrapes as we'll visit fewer pages overall.

**Comment by hancush** [comment]
Done in #93.
